### ISSUE TITLE
NGINX Change Port

### ISSUE THREAD

**Issue by rnaby** [WPN-XM/WPN-XM#547] opened 2016-03-06 12:28 UTC
Is there any option to change NGINX default port ? I mean I wanna change the default port 80 to 8056. How can I do that ?

**Comment by klonos** [comment] 2016-03-06 18:43
Yes, edit your `\bin\nginx\conf\nginx.conf` file and change this line:

`listen       127.0.0.1:80;`

to this:

`listen       127.0.0.1:8056;`

Then restart nginx. That should work.

**Comment by jakoch** [comment] 2016-03-09 20:19
Thanks you for providing support, Gregory! 

I guess, you want a form field to change the port - so that you don't have to edit the file manually, right?
I guess i have to implemented everything on my own....

**Comment by klonos** [comment] 2016-03-09 20:42
> Thanks you for providing support, Gregory! 

It's the least I can do to thank you for this very useful application you've put together. Besides, if I can save you a few minutes from doing issue queue support, then you'll have more time to fix bugs and implement new features to make WPN-XM more awesome :wink:

**Comment by jakoch** [comment] 2016-05-02 09:54
I'm closing this ticket, because support was provided and the feature request is a duplicate/part of #327. Because of the high-number of requests, i've re-scheduled the "add Config Tab to Configure Ports" / Port Changer GUI ticket and added it to the v0.8.7 milestone.

----
- [x] support
- [x] feature request: duplicate of https://github.com/WPN-XM/WPN-XM/issues/327

**Closed by jakoch** 2016-05-02 09:54 UTC
Labels: support
