### ISSUE TITLE
[feature proposal] DualServer DNS/DHCP Server

### ISSUE THREAD

**Issue by jhit** [WPN-XM/WPN-XM#369] opened 2015-04-08 07:32 UTC
http://dhcp-dns-server.sourceforge.net/

I use this tiny DNS/DHCP Server only in DNS mode to map the wildecard Domain *.dev to localhost.
I have a default configuration for Nginx for all vHosts matching the *.dev schema.
This way I can create new development projects just by creating a folder /projectname/public in my www/ directory.
No fiddling with hosts file.

Disadvantages: 
If you want this in a environment where only DHCP configured network interfaces are available you need to install a Loopback adapter and assign a static IP.

**Comment by jakoch** [comment] 2015-04-08 17:08
Hey Jürgen,
thank you for this feature request. 
It goes in the direction of easier mapping of project folders to server blocks / *.dev domains. 
The issue is long overdue. I will test the tool (which is quite a gem) and consider it for the changeset regarding easier server block management.

**Comment by klonos** [comment] 2015-04-08 19:16
Very useful tool indeed! Thanx @jhit

**Comment by jhit** [comment] 2015-04-08 21:19
The one big issue with this tool is the fact that it does not listen on 127.0.0.1. I already requested this feature some time ago, but the developer did not like the idea. For WPN-XM it would probably be the best solution to create a patch for the tool that allows it to listen on localhost. Then the requirement of a fixed IP address would go away and the workaround with the loopback device would be unnecessary. Just like DNSmasq on linux ;)

**Comment by jakoch** [comment] 2015-09-03 11:02
I've looked into this issue again. The tool itself is quite powerful, but really not easy to integrate.

When we focus on just providing the feature of wildcard domain resolution `*.dev` via a DNS tool, then a tool like Acrylic DNS would be a better fit. Its easier to handle, because its uses a "hosts" file approach with some added features, like wildcard support. An additional benefit is, that the DNS resolutions are cached, which speeds the initial connection up. http://mayakron.altervista.org/wikibase/show.php?id=AcrylicHome

The integration problem remains:
Its complicated to install a proxy from the innosetup installer.
Firstly, this requires a dialog to ask, where the proxy should be installed, for instance, you can add it at connection level or just to the default browser. Secondly, the service must be registered.
The amount of Pascal code needed to solve this is huge.

To cut a long story short: the fastest way for an integration is to ship it with a default config, but leave it deactivated and explain the necessary steps to get it up and running somewhere in the docs.

**Comment by jakoch** [comment] 2015-11-13 21:04
I'm closing the issue, because i will not add or implement the initially suggested DHCP/DNS software.

The underlying problem is the missing vhost/server block support of the webinterface or the SCP.
The development focus is on automatical creation of vhost entries into the hosts file and creation of nginx server blocks based on a folder scan or directly after the creation of a new project from the webinterface or the SCP. Referencing the unresolved issues #2 and #94.

**Closed by jakoch** 2015-11-13 21:04 UTC
Labels: feature
