### ISSUE TITLE
WPN-XM Server Control Panel has stopped working

### ISSUE THREAD

**Issue by lovebdsobuj** [WPN-XM/WPN-XM#610] opened 2016-09-04 02:47 UTC
**WPN-XM Web Server Working as well.**

But when I checked 
- [x] **`Start minimized to Tray?`**

**WPI/I-XM Sewer Control Panel (Not Responding)**
and
WPN-XM Server Control Panel has stopped working.
![screenshot_2016 09 04_08h27m46s_002_](https://cloud.githubusercontent.com/assets/10352682/18228711/12c5682a-727c-11e6-8fda-3d4070f3efb3.png)

**Platform: Windows 10 / 32 bit**
_**WPN-XM Version 0.8.5+0a7e025**_

**Comment by jakoch** [comment] 2016-09-04 10:53
Hey Love,

thank you for reporting this issue and helping making WPN-XM better.

I remember, that i already fixed this bug (see https://github.com/WPN-XM/WPN-XM/issues/591 and the [SCP Changelog](https://github.com/WPN-XM/server-control-panel/blob/master/Changelog.md#unreleased)). 
But i didn't release a new version of the SCP (containing this bugfix), yet.
The workaround is to set `startminimized` to `0` in `wpn-xm.ini`.

Regards, Jens

**Comment by lovebdsobuj** [comment] 2016-09-04 15:05
Thank you Jens,
It's working by manually editing `wpn-xm.ini` file `startminimized` to `0`.

**Off-Topic**:
I think it will be good if `webinterface` links put into `localhost` >
`index` file.

Visiting localhost and `redirecting` to `webinterface` page doesn't look good.

`tools` folder kept as well.

What do you think? How would it be?

**Comment by lovebdsobuj** [comment] 2016-09-04 15:15
Thank you Jens,
It's working by manually editing `wpn-xm.ini` file `startminimized` `1` to `0`.

**Off-Topic:**
I think it will be good if `webinterface` links put into `localhost` > `index` file.

Visiting localhost and `redirecting` to `webinterface` page doesn't look good.

`tools` folder kept as well.

What do you think? How would it be?

**Comment by jakoch** [comment] 2016-09-04 15:55
I will start working on new releases soon. 
For now, i'm glad the workaround did it.

----

Regarding the redirect: 

It's basically the 3 seconds wait time, which is annoying, right?
I could remove the [3 seconds timer before the redirect happens](https://github.com/WPN-XM/WPN-XM/blob/master/www/index.html#L7) and do a immediate redirect (without waiting). Would that be better?

Another simple option is to delete `www/index.html` or rename it to `www/webinterface.html`, when you open `http://localhost` you will get the directory listing of the www folder

We could also add a vhost for `http://localhost/tools/webinterface`, e.g. `http://wpn-xm.webinterface` or `http://webinterface.dev`. Both URLs are probably too long, but i'm lacking a good idea for a nice and short one. I'm open for suggestions.

**Comment by lovebdsobuj** [comment] 2016-09-06 14:31
Some short domain names,
- http://wpn.xm/
- http://wpn.xm/cpanel

But is there problem about vhosts, sometimes vhosts file lost newly added domain names.

**Off-Topic:**
I'm thinking about a tools that generate `\bin\nginx\conf\domains-enabled` files.
![wpn-xm server add new domain name](https://cloud.githubusercontent.com/assets/10352682/18277592/d224c7d8-7470-11e6-9255-35ae64b45a4e.png)

**Comment by jakoch** [comment] 2016-09-06 14:41
Ok, i like `http://wpn.xm/`. Let's use that as the new vhost for the webinterface.
We can't use "cPanel", because that's a hosting frontend panel (http://cpanel.com/).

> But is there problem about vhosts, sometimes vhosts file lost newly added domain names.

This might be a possible bug. Can you provide steps to reproduce the issue, so that i can find and address the bug.

> I'm thinking about a tools that generate \bin\nginx\conf\domains-enabled files.

Yes, that idea is around a long time, see #2. 
Our goal is to "create a new project" and "automatically create the vhost" file and the "hosts" entry.

**Comment by klonos** [comment] 2016-09-06 16:09
> Ok, i like `http://wpn.xm/`. Let's use that as the new vhost for the webinterface.

Smart 😄 👍

**Comment by jakoch** [comment] 2016-09-18 17:58
I've created new issues for the ideas and suggestions from our discussion.
Original issue is a duplicate: closing.

**Closed by jakoch** 2016-09-18 17:58 UTC
Labels: duplicate bug, server control panel
